name: Build and Upload

on:
  push:
    branches: ['*\+vaccel']
    tags: ['v*\+vaccel*']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: read-all

jobs:
  build-and-upload:
    name: Build and Upload
    uses: ./.github/workflows/build-docker-image.yml
    permissions:
      contents: read
      packages: read
      pull-requests: read
      id-token: write
    with:
      release: true
    secrets: inherit

  update-release:
    needs: build-and-upload
    name: Update Release
    if: always()
    uses: nubificus/vaccel/.github/workflows/update-release.yml@main
    with:
      create-github-release: false
      result: ${{ needs.build-and-upload.result }}
    secrets: inherit
